language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree

gemfile:
  - gemfiles/rails_30.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile

script: 'bundle exec rake'
