language: ruby

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile

sudo: false

script: 'bundle exec rake'

matrix:
  exclude:
  - rvm: 2.3.8
    gemfile: gemfiles/rails_60.gemfile
  - rvm: 2.4.6
    gemfile: gemfiles/rails_60.gemfile
