language: ruby

rvm:
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/rails_40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_41.gemfile

script: 'bundle exec rake'
